# -*- mode: ruby -*-
# vi: set ft=ruby :

class KernelUpdateInstaller < VagrantVbguest::Installers::RedHat
  def install(opts=nil, &block)
    communicate.sudo('yum -y update kernel', opts, &block)
    super
  end
end

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  # Custom installer to ensure proper installation of kernel headers for VBOX Guest Additions
  config.vbguest.installer = KernelUpdateInstaller

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  config.vm.network "forwarded_port", guest: 1234, host: 1234
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 27017, host: 27017

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "./../docker", "/opt/docker"

  # Provider-specific configuration tofine-tune various backing providers for Vagrant. These expose provider-specific options.
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  # Enable provisioning with a shell script.
  config.vm.provision :shell, path: "./provision/docker-provision.sh"
end
